apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasklist-backend-deployment
  namespace: tasklist-ns
  labels:
    app: tasklist-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tasklist-backend
  template:
    metadata:
      labels:
        app: tasklist-backend
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox:1.36
          command: ["sh", "-c", "until nc -z tasklist-db-service 5432; do echo Waiting for db; sleep 2; done;"]
      containers:
        - name: tasklist-backend
          image: anssuy1/tasklist-backend:8a5bd4cd80b832506ed0b1a6fa9adae58e478fc8
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: tasklist-config
            - secretRef:
                name: tasklist-secrets
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
